on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: run docker
        run: docker build -t cv_docker .
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: cv_docker
          path: /cv/main.pdf
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: cv
          
  public_cv:
    name: public_cv
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: cv_pdf
      - name: download cv
        uses: actions/download-artifact@v2
        with:
          name: cv
      - run: |
          git add main.pdf
          git commit -m "Add cv"
          git push
        
    
